name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        go:
          - '1.21'
          - '1.22'
          - '1.23'
          - '1.24'
          - '>=1.25.0-rc.1'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - run: go test -v -tags swiss_invariants

  linux-noswissmap:
    strategy:
      matrix:
        go:
          - '1.24'
          - '>=1.25.0-rc.1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version:  ${{ matrix.go }}

      - run: GOEXPERIMENT=noswissmap go test -v

  linux-race:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.24'
          - '>=1.25.0-rc.1'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - run: go test -v -race


  linux-32bit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.24'
          - '>=1.25.0-rc.1'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - run: GOARCH=386 go test -v -tags swiss_invariants

  linux-qemu-s390x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.24.4'
          - '1.25rc1'
    steps:
      - uses: actions/checkout@v2

      - name: Install qemu
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          qemu-s390x-static --version

      - name: ubuntu-core:s390x-focal
        shell: bash
        run: |
          docker run --rm --privileged \
            -v "${{ github.workspace }}:/swiss" \
            multiarch/ubuntu-core:s390x-focal \
            bash -c "
                uname -a &&
                lscpu | grep Endian &&
                apt-get update &&
                apt-get install -y wget &&
                wget -q 'https://go.dev/dl/go${{ matrix.go }}.linux-s390x.tar.gz' &&
                tar xzf 'go${{ matrix.go }}.linux-s390x.tar.gz' -C /usr/local &&
                export PATH="$PATH:/usr/local/go/bin" &&
                cd /swiss &&
                go version &&
                go env &&
                go test -v ./... &&
                go test -v -tags swiss_invariants ./...
            "
